#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.all,expects="1+"
---
#@overlay/match missing_ok=True
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/disable-original: true
